<?php

namespace AppBundle\Repository;

/**
 * AssociationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
