<?php

namespace AppBundle\Repository;

/**
 * NewsletterEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterEventRepository extends \Doctrine\ORM\EntityRepository
{
}
