<?php

namespace AppBundle\Repository;

/**
 * QuizCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
