<?php

namespace AppBundle\Repository;

/**
 * QuizScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizScoreRepository extends \Doctrine\ORM\EntityRepository
{
}
