app_index:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
app_associations:
    path:     /acteurs
    defaults: { _controller: "AppBundle:Default:associations" }
app_events:
    path:     /actions
    defaults: { _controller: "AppBundle:Default:events" }
#app_quiz:
#    path:     /quizz
#    defaults: { _controller: "AppBundle:Default:quiz" }
#app_quiz_result:
#    path:     /quizz/resultats
#    defaults: { _controller: "AppBundle:Default:quizResult" }
app_association:
    path:     /acteur/{id}/{name}
    defaults: { _controller: "AppBundle:Default:association" }
    requirements:
        id: \d+
app_event_ics:
    path:     /action/{id}/ics
    defaults: { _controller: "AppBundle:Default:ics" }
    requirements:
        id: \d+
app_event:
    path:     /action/{id}/{name}
    defaults: { _controller: "AppBundle:Default:event" }
    requirements:
        id: \d+
app_archives:
    path:     /archives
    defaults: { _controller: "AppBundle:Default:archives" }
app_archives_page:
    path:     /archives/{year}-{month}
    defaults: { _controller: "AppBundle:Default:archives" }
    requirements:
        year: \d+
        month: \d+
app_search:
    path:     /recherche
    defaults: { _controller: "AppBundle:Default:search" }
app_legal_terms:
    path:     /mentions-legales
    defaults: { _controller: "AppBundle:Default:legalTerms" }
app_map:
    path:     /carte
    defaults: { _controller: "AppBundle:Default:map" }
app_admin_association:
    path:     /admin/acteur
    defaults: { _controller: "AppBundle:Admin:index" }
app_admin_events:
    path:     /admin/action
    defaults: { _controller: "AppBundle:Admin:events" }
app_admin_index:
    path:     /admin
    defaults: { _controller: "AppBundle:Admin:calendar" }
app_admin_event:
    path:     /admin/action/{id}
    defaults: { _controller: "AppBundle:Admin:event" }
    requirements:
        id: \d+
app_admin_event_document:
    path:     /admin/action/{id}/document
    defaults: { _controller: "AppBundle:Admin:eventDocument" }
    requirements:
        id: \d+
app_admin_search_place:
    path:     /admin/lieux/recherche
    defaults: { _controller: "AppBundle:Admin:searchPlace" }
app_superadmin_users:
    path:     /admin/superadmin/utilisateur
    defaults: { _controller: "AppBundle:SuperAdmin:users" }
app_superadmin_associations:
    path:     /admin/superadmin/acteur
    defaults: { _controller: "AppBundle:SuperAdmin:associations" }
app_superadmin_events:
    path:     /admin/superadmin/action
    defaults: { _controller: "AppBundle:SuperAdmin:events" }
app_superadmin_event:
    path:     /admin/superadmin/action/{id}
    defaults: { _controller: "AppBundle:SuperAdmin:event" }
    requirements:
        id: \d+
app_superadmin_places:
    path:     /admin/superadmin/lieu
    defaults: { _controller: "AppBundle:SuperAdmin:places" }
app_superadmin_place:
    path:     /admin/superadmin/lieu/{id}
    defaults: { _controller: "AppBundle:SuperAdmin:place" }
    requirements:
        id: \d+
app_superadmin_quiz_scores:
    path:     /admin/superadmin/quizz
    defaults: { _controller: "AppBundle:SuperAdmin:quizScores" }
app_superadmin_association_document:
    path:     /admin/superadmin/acteur/{id}/document
    defaults: { _controller: "AppBundle:SuperAdmin:associationDocument" }
    requirements:
        id: \d+
app_superadmin_association_type:
    path:     /admin/superadmin/association/type
    defaults: { _controller: "AppBundle:SuperAdmin:associationTypes" }
        
app_superadmin_newsletters:
    path:     /admin/superadmin/lettre
    defaults: { _controller: "AppBundle:SuperAdmin:newsletters" }
app_superadmin_newsletters_highlight:
    path:     /admin/superadmin/lettre/{id}/actions
    defaults: { _controller: "AppBundle:SuperAdmin:highlightInNewsletter" }
    requirements:
        id: \d+

app_admin_workshop:
    path:     /admin/atelier
    defaults: { _controller: "AppBundle:Admin:workshop" }
app_admin_workshops:
    path:     /admin/ateliers
    defaults: { _controller: "AppBundle:Admin:workshops" }
app_admin_workshop_events:
    path:     /admin/reunions
    defaults: { _controller: "AppBundle:Admin:workshopEvents" }
        
app_newsletter:
    path:     /lettre/{startY}-{startM}-{startD}/{endY}-{endM}-{endD}
    defaults: { _controller: "AppBundle:Default:newsletter" }
    requirements:
        startY: \d+
        startM: \d+
        startD: \d+
        endY: \d+
        endM: \d+
        endD: \d+
app_newsletter_id:
    path:     /lettre/{id}
    defaults: { _controller: "AppBundle:Default:newsletter" }
    requirements:
        id: \d+
        
app_workshop:
    path:     /atelier/{id}/{name}
    defaults: { _controller: "AppBundle:Default:workshop" }
    requirements:
        id: \d+
app_workshops:
    path:     /ateliers
    defaults: { _controller: "AppBundle:Default:workshops" }

