app_index:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
app_license:
    path:     /licence
    defaults: { _controller: "AppBundle:Default:license" }
app_associations:
    path:     /acteurs
    defaults: { _controller: "AppBundle:Default:associations" }
app_events:
    path:     /actions
    defaults: { _controller: "AppBundle:Default:events" }
app_quiz:
    path:     /quizz
    defaults: { _controller: "AppBundle:Default:quiz" }
app_quiz_result:
    path:     /quizz/resultats
    defaults: { _controller: "AppBundle:Default:quizResult" }
app_association:
    path:     /acteur/{id}/{name}
    defaults: { _controller: "AppBundle:Default:association" }
    requirements:
        id: \d+
app_event:
    path:     /action/{id}/{name}
    defaults: { _controller: "AppBundle:Default:event" }
    requirements:
        id: \d+
app_archives:
    path:     /archives
    defaults: { _controller: "AppBundle:Default:archives" }
app_archives_page:
    path:     /archives/{page}
    defaults: { _controller: "AppBundle:Default:archives" }
    requirements:
        page: \d+
app_admin_association:
    path:     /admin/acteur
    defaults: { _controller: "AppBundle:Admin:index" }
app_admin_events:
    path:     /admin/actions
    defaults: { _controller: "AppBundle:Admin:events" }
app_admin_index:
    path:     /admin
    defaults: { _controller: "AppBundle:Admin:calendar" }
app_admin_event_document:
    path:     /admin/action/{id}/document
    defaults: { _controller: "AppBundle:Admin:eventDocument" }
    requirements:
        id: \d+
app_admin_search_place:
    path:     /admin/lieux/recherche
    defaults: { _controller: "AppBundle:Admin:searchPlace" }
app_superadmin_users:
    path:     /admin/superadmin/utilisateur
    defaults: { _controller: "AppBundle:SuperAdmin:users" }
app_superadmin_associations:
    path:     /admin/superadmin/acteur
    defaults: { _controller: "AppBundle:SuperAdmin:associations" }
app_superadmin_events:
    path:     /admin/superadmin/action
    defaults: { _controller: "AppBundle:SuperAdmin:events" }
app_superadmin_quiz_scores:
    path:     /admin/superadmin/quizz
    defaults: { _controller: "AppBundle:SuperAdmin:quizScores" }

